---
# tasks file for register_components
- hosts: cpm
  serial: 1
  tasks:
  - name: Register cpm
    include_role: 
      name: cpm
    vars:
      - cpm_extract: false
      - cpm_prerequisites: false
      - cpm_install: false
      - cpm_postinstall: false
      - cpm_hardening: false
      - accept_eula: "Yes"
      - ansible_password: "{{ ansible_password }}"
      - vault_username: "administrator"
      - cpm_registration: true
      
- hosts: pvwa
  serial: 1
  tasks:
  - name: Register pvwa
    include_role: 
      name: pvwa
    vars:
      - pvwa_extract: false
      - pvwa_prerequisites: false
      - pvwa_install: false
      - pvwa_postinstall: false
      - pvwa_hardening: false
      - ansible_password: "{{ ansible_password }}"
      - accept_eula: "Yes"
      - pvwa_registration: true
      
- hosts: psm
  serial: 1
  tasks:
  - name: Register psm
    include_role: 
      name: psm
    vars:
      - psm_extract: false
      - psm_prerequisites: false
      - psm_install: false
      - psm_postinstall: false
      - psm_hardening: false
      - accept_eula: "Yes"
      - ansible_password: "{{ ansible_password }}"
      - vault_username: "administrator"
      - psm_disable_nla: "Yes"
      - psm_out_of_domain: false
      - psm_registration: true
  