---

# pvwa git repo
- src: https://github.com/cyberark/pvwa.git
  scm: git
  version: v11.4

# cpm git repo
- src: https://github.com/cyberark/cpm.git
  scm: git
  version: feature-cpm-user

# psm git repo
- src: https://github.com/cyberark/psm.git
  scm: git
  version: v11.4
