---

# pvwa git repo
- src: https://github.com/cyberark/pvwa.git
  scm: git
  version: v11.4

# cpm git repo
- src: https://github.com/cyberark/cpm.git
  scm: git
  version: v11.4

# psm git repo
- src: https://github.com/cyberark/psm.git
  scm: git
  version: v11.4

# psmp git repo
- src: https://github.com/dviryamin/psmp.git
  scm: git
  version: v11.3
