---

# pvwa git repo
- src: https://github.com/cyberark/pvwa.git
  scm: git
  version: develop

# cpm git repo
- src: https://github.com/cyberark/cpm.git
  scm: git
  version: develop

# psm git repo
- src: https://github.com/cyberark/psm.git
  scm: git
  version: develop
