# pvwa git repo
- src: git@github.com:cyberark/pvwa.git
  scm: git
  
# cpm git repo
- src: git@github.com:cyberark/cpm.git
  scm: git
  
# psm git repo
- src: git@github.com:cyberark/psm.git
  scm: git