---
# file: main.yml

- hosts: localhost
  connection: local
  vars_prompt:

    - name: accept_eula
      prompt: "Please accept EULA"
      private: no

    - name: vault_ip
      prompt: "Please enter the Vault ip address"
      private: no

    - name: vault_password
      prompt: "Please enter the Vault Administrator password"
      private: yes

    - name: ansible_user
      prompt: "Please enter the Hosts Administrator username"
      private: no

    - name: ansible_password
      prompt: "Please enter the Hosts Administrator password"
      private: yes

    - name: cpm_zip_file_path
      prompt: "Please enter cpm package location (etc. /tmp/pas_packages/cpm.zip)"
      private: no

    - name: pvwa_zip_file_path
      prompt: "Please enter pvwa package location (etc. /tmp/pas_packages/pvwa.zip)"
      private: no

    - name: psm_zip_file_path
      prompt: "Please enter psm package location (etc. /tmp/pas_packages/psm.zip)"
      private: no

  tasks:

    - name: Set required parameters from prompt
      include_tasks: set_facts.yml

- hosts: cpm:pvwa:psm
  strategy: free

  tasks:

    - include_tasks: cpm.yml
      when: "'cpm' in group_names"
    - include_tasks: pvwa.yml
      when: "'pvwa' in group_names"
    - include_tasks: psm.yml
      when: "'psm' in group_names"


# PSM Register Component Requires the First PVWA IP Address

- hosts: cpm:pvwa:psm
  serial: 1
  tasks:

    - include_tasks: register_cpm.yml
      when: "'cpm' in group_names"
    - include_tasks: register_pvwa.yml
      when: "'pvwa' in group_names"
    - include_tasks: register_psm.yml
      vars:
        pvwa_ip: "{{ groups['pvwa'][0] }}"
      when: "'psm' in group_names"
