---
windows:
  children:
    pvwa:
      hosts:
        34.244.60.242:
        34.254.205.95:
    cpm:
      hosts:
        34.241.139.113:
        18.203.222.201:
    psm:
      hosts:
        34.254.192.231:
        34.243.155.214:
        
# windows:
#   children:
#     pvwa:
#       hosts:
#         1.1.1.1:
#     cpm:
#       hosts:
#         63.33.190.159:
#     psm:
#       hosts:
#         2.2.2.2: